### ISSUE TITLE
Error: Can't create styles

### ISSUE THREAD

**Issue by jonaschafer** [kaleidocode-app/chroma#2]
Hey there! I really want this plugin to work - we have about 50 styles - but I just get this error: https://zappy.zapier.com/2F40FAB6-2B50-4613-A2C3-046726A5B699.png

I've tried: 
* Renaming the layers
* Creating styles in a Draft file
* Force quitting Chrome
* Hard refreshing Chrome

...but no dice. Please help!

**Comment by miguelsolorio** [comment]
@jonaschafer thanks for trying out the plugin! So this means that you're trying to create a style from an item that already has a color style. This is so that duplicates don't get added again. Can you double check to see if this is true? If not, can you post a GIF showing what you're trying to do?

**Comment by jonaschafer** [comment]
Sure! Here's what that process looks like: https://www.loom.com/share/37f940a8700b471099bccaf79182809d

**Comment by miguelsolorio** [comment]
Thanks so much, that's very helpful! I can't seem to reproduce this on my side (even tried it in Chrome). Do you mind attaching you .fig file and see if i can inspect your file? Something seem very strange.

**Comment by jonaschafer** [comment]
Sure! And thanks for being so speedy on these replies :) 
https://www.figma.com/file/PC8ADWEP46zB4l5NbXoQox/Untitled?node-id=0%3A1

**Comment by miguelsolorio** [comment]
Awesome, thanks! I already hit the error trying your rectangles so let me inspect.

**Comment by miguelsolorio** [comment]
Ah, ok I think I know this issue. Did you copy these rectangles from another file that previously had a color style applied to them?

**Comment by jonaschafer** [comment]
I did! Yep.

**Comment by miguelsolorio** [comment]
So that's a currently a bug in the Figma plugin api that doesn't properly clear style properties when going to another file. They're working on a fix.

**Comment by jonaschafer** [comment]
Right on. Thanks for clarifying! I'm relieved it isn't user-error 👍
