### ISSUE TITLE
Order of styles not based on layer order

### ISSUE THREAD

**Issue by wilsonminer** [kaleidocode-app/chroma#3]
In the readme example the created styles appear to be in the order they appear in the layer palette. This is the behavior I would expect. When I use the plugin they appear in a different order when created in the styles palette, and I need to manually reorder them to recreate the intended order.

Layer order:
<img width="190" alt="Screen Shot 2019-08-20 at 10 51 49 AM" src="https://user-images.githubusercontent.com/6052/63371631-4fbf4c80-c339-11e9-84f2-6101ba7cd663.png">

Created styles:
![image](https://user-images.githubusercontent.com/6052/63371651-5cdc3b80-c339-11e9-8b32-864e7c856d6d.png)

**Comment by miguelsolorio** [comment]
This is actually a bug in the sorter logic, it should sort from largest to smallest. From the Figma API there is no guarantee that the layers will always be in the layer order. 

I'll fix the sorting bug.

**Comment by miguelsolorio** [comment]
This is now fixed and will sort it from ascending + largest to smallest regardless of layer order:

![gif](https://user-images.githubusercontent.com/35271042/63740119-a7335000-c844-11e9-8cb7-1646b378e110.gif)

**Comment by nimbling** [comment]
Personally, I would expect it to sort alphabetically.

Currently, in my view, it's behaving reversed. Am I the only one?

This is what I get now, but I'd like the resulting styles to match the source layer order.

<img width="213" alt="Resulting Styles" src="https://user-images.githubusercontent.com/821411/64864461-71a9a780-d637-11e9-860e-6550be28aa5e.png">
<img width="219" alt="Source Layers" src="https://user-images.githubusercontent.com/821411/64864464-71a9a780-d637-11e9-951e-7c2ffc064f49.png">

**Comment by nimbling** [comment]
All I had to do was make a clone of the plugin, and comment out the "ref.reverse();" line out of the .js and .ts files, then load that version of the plugin and it now behaves the way I need it.

Perhaps others find this useful, or is it possible to provide an option?

Thanks a bunch! :)

**Comment by miguelsolorio** [comment]
@nimbling I created a [separate issue](https://github.com/kaleidocode-app/chroma/issues/5) for this, feel free to create new issues for feature requests 😄

**Comment by miguelsolorio** [comment]
@nimbling I've removed the reverse sort and will re-add this as an option later.
