### ISSUE TITLE
Rename Plugin for more visibility

### ISSUE THREAD

**Issue by ghost** [kaleidocode-app/chroma#4]
I struggled to find the plugin I had seen in my twitter feed. 

`Chroma` is great but when people look for the tool it does not come to mind straight away.
renaming it to 
`chroma palette` or `chroma colors` or `chroma theme`

will help a lot  IMO

**Comment by nimbling** [comment]
+1 for this!

**Comment by miguelsolorio** [comment]
Done 😄 

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/35271042/67360161-0ac2bc80-f51a-11e9-868d-2dfb1cf2618d.png">
